services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "5173:5173"
    depends_on:
      - api
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - my_network

  api:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    command: npm run dev
    container_name: api
    networks:
      - my_network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
